# Generated by Django 5.2.1 on 2025-06-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='media/profiles/user.png', upload_to='profiles/'),
        ),
    ]
