# Generated by Django 5.2.1 on 2025-06-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_profile_address_profile_insta_link_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='proffesion',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
